### ISSUE TITLE
drawing over the objects rather than in the air

### ISSUE THREAD

**Issue by khurramengr** [googlecreativelab/justaline-android#3]
I was trying to draw over the object rather than in the air, currently whenever i draw a line over some object it draws in the air at some specific distance from the camera, and while moving the camera towards that object the camera passes through that line and line doesn't stay on the object anymore.
Currently I've tried changing the **strokeDrawDistance** value inside the **AppSettings.java** but that doesn't seem working.

**Comment by khurramengr** [comment]
@HalfdanJ can you guide me further?

**Comment by HalfdanJ** [comment]
It would be a larger undertaking then a simple change. Currently the app doesnt try to do any surface detection. So in order to do what you talk about, you'd have to do surface detection, and set the strokeDrawDistance accordingly to the distance to the surface.

**Comment by khurramengr** [comment]
@HalfdanJ I've managed to achieve this with the help of **hitTest** on frame.
Performing hitTest with all the points involved in a drawing and then getting distance of every **HitResult** and drawing the line at maximum distance achieved from all the **hitResult**s.
But the issue is that there is no anchor to which this drawing is attached to, and hence isn't stable and moves most of the times, moreover if hitTest comes up with empty **HitResult**s what do we do in that case?

**Comment by khurramengr** [comment]
I am trying to achieve something like [this](https://vivar.me/).
Sticking the drawing to/around the object is the core implementation in my case.
Can you guide me further how to achieve this?

**Comment by khurramengr** [comment]
@HalfdanJ can you help me?

**Comment by HalfdanJ** [comment]
Hmm, so I guess there are two directions you could go, either doing it as you do know by finding hit results, or by using surfaces. Using surfaces will of course limit the surfaces it works on a lot, but will solve the issue you have of unresolved areas, whereas your current approach works on more versatile objects. 

Maybe there is an approach where you use hit results to estimate a distance, and use that distance as the drawing distance?

**Comment by HalfdanJ** [comment]
You can also try and leave an anchor at a hit result, and use that as the reference point for the drawing. The renderer should support anchors moving around, since we use that for shared drawings

**Comment by anilmaddala** [comment]
@khurramengr Did you figure out how to do it? I am looking into something similar, do you mind sharing your code base or pushing a Pull request?

**Comment by krunalpaliwal** [comment]
@khurramengr did you find any solution for this? I facing the same issue. I have achieved the draw points drawing is also placed on that points but after that, it changes its position and moves around.
@HalfdanJ any hint for this?
